name: Dashboard REST API Automation

on:
  repository_dispatch:
    types: [automation]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Dashboard API Tests'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Build with maven and run tests
        run: mvn test -Dtest=TestsRunner